### ISSUE TITLE
error on creating migration for indices

### ISSUE THREAD

**Issue by OriHoch** [hasadna/open-bus-stride-db#14]
I'm getting this error from alembic and the migration file is created empty -
/Users/shayadler/Hasadna/OpenBus/open-bus-stride-db/venv/lib/python3.9/site-packages/alembic/ddl/postgresql.py:221: UserWarning: autogenerate skipping functional index idx_gtfs_ride_start_time; not supported by SQLAlchemy reflection util.warn( /Users/shayadler/Hasadna/OpenBus/open-bus-stride-db/venv/lib/python3.9/site-packages/alembic/ddl/postgresql.py:221: UserWarning: autogenerate skipping functional index idx_gtfs_ride_stop_arrival_time; not supported by SQLAlchemy reflection util.warn( /Users/shayadler/Hasadna/OpenBus/open-bus-stride-db/venv/lib/python3.9/site-packages/alembic/ddl/postgresql.py:221: UserWarning: autogenerate skipping functional index idx_siri_ride_scheduled_start_date; not supported by SQLAlchemy reflection util.warn(

Note that the error is written both on my new indexes and also on an existing one (idx_siri_ride_scheduled_start_date), even though I saw in the docs that --autogenerate should identify new indexes. Happened to you? Anyway I'll create the file manually..

**Comment by ShayAdler** [comment]
Followed the [steps](https://github.com/hasadna/open-bus-stride-db#make-changes-to-the-db-model) for generating a migration file using alembic, and after adding the following [indexes](https://github.com/hasadna/open-bus-stride-db/pull/15), and got the error above.

**Comment by OriHoch** [comment]
autogenerate doesn't detect textual SQL statements, so they have to be added manually

**Comment by OriHoch** [comment]
in most cases, there is no need to add textual SQL statements, in this case too, adding `index=True` is better and works with autogenerate, as I did in this commit - https://github.com/hasadna/open-bus-stride-db/commit/85e08a1c2570f86348525a9e4738ff986a003393
