### ISSUE TITLE
RFC: Create readonly SQL user for exploration on the bus DB server

### ISSUE THREAD

**Issue by BackSlasher** [hasadna/open-bus-stride-db#18]
Ideally it should be part of `/db-scripts/initialize.sh`, but this file is probably part of `orihoch/data4dappl-db:v0.2.15`.
However, I doubt that we want to run this file again, as it might delete some things.
I suggest we either:
## Manually create a user for readonly people
This user will have a password expiration (https://stackoverflow.com/a/45792269), so we won't have stale passwords
The user will have a query timeout limit (https://stackoverflow.com/a/63934545) so the user won't hurt the app's runtime performance

## Create a "warehouse db" for exploration
Create another database server which is only used for research,  which has readonly users manually created for people.
This database will use something like logshipping, or cron-update form the nightly SQL dump to keep fresh.
Any queries on it won't impact the production server

## Create a PostgreSQL Studio installation
This will allow us to keep the readonly password hidden (or maybe managed with some certificate instead of password), and only allow access to the studio webui to Hasadna members that we trust.
We can also configure the studio to limit query time and whatnot to avoid impacting the main db.

This is not urgent, and I'm happy to hear whathever opinions other people have.

**Comment by BackSlasher** [comment]
After giving it some thought, I like the "warehouse db" solution the best. We could grant many people access without ever fearing affecting any prod app we'll have

**Comment by OriHoch** [comment]
oops, didn't see this issue, notifications were turned off for this repo.. turned it back on now

**Comment by OriHoch** [comment]
moved it to open-bus-stride-db repo

**Comment by OriHoch** [comment]
we have a read only user which we can give to internal developers working on the stride project itself.

for external developers that want to do data exploration or develop apps on top of stride, we don't want to provide a DB interface as this limits our options to change data structure and interfaces in the future and is a point of contact which is harder to support long-term.

adding a query timeout is a good idea for our read only user, and possibly also for out api user, I will open another issue about that

closing the issue for now, but feel free to reopen

**Comment by OriHoch** [comment]
> Ideally it should be part of `/db-scripts/initialize.sh`, but this file is probably part of `orihoch/data4dappl-db:v0.2.15`. 

this file is not relevant for open-bus-stride-db, it's used for a different project

> This user will have a password expiration (https://stackoverflow.com/a/45792269), so we won't have stale passwords

I don't care too much about stale passwords or security because there is no sensitive data in the DB, it's all public data

> Create another database server which is only used for research, which has readonly users manually created for people. This database will use something like logshipping, or cron-update form the nightly SQL dump to keep fresh. Any queries on it won't impact the production server

that's too resource intensive for us, we try to keep resources to a minimum, but of course, if some volunteer wants to finance this, I will be happy to help integrate this

> ## Create a PostgreSQL Studio installation
> This will allow us to keep the readonly password hidden (or maybe managed with some certificate instead of password), and only allow access to the studio webui to Hasadna members that we trust. We can also configure the studio to limit query time and whatnot to avoid impacting the main db.

This sounds very similar to our Redash which already can allow to do that - https://redash.hasadna.org.il/ - the stride DB is accessible there, it's just only open to specific users
